name: Default Qt Build

on:
  push:
    paths-ignore:
      - 'dist/**'
      - 'doc/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: xenosb/qt5/android-arm64-v8
  QT_STABLE_VERSION: 6.9.1
  QT_VERSION: 6.9.2
  ANDROID_SDK_VERSION: 35
  ANDROID_SDK_ROOT: /opt/android-sdk
  ANDROID_BUILD_TOOLS_VERSION: 35.0.0
  ANDROID_NDK_VERSION: 26.1.10909125
  BUILD_TYPE: Release

jobs:
  docker:
    name: Docker image
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        config:
        - {
            name: "Android arm64-v8",
            artifact: "android-arm64-v8",
            architecture: "arm64-v8a",
            image: "ghcr.io/xenosb/qt5/android-arm64-v8:latest"
        }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Check if Dockerfile chaged
        id: changed-dockerfile
        uses: tj-actions/changed-files@v35
        with:
          files: |
            docker/${{ matrix.config.artifact }}.dockerfile

      - name: Build docker image
        if: steps.changed-dockerfile.outputs.any_changed == 'true'
        run: |
          if docker pull ${{ steps.meta.outputs.tags }}; then
            echo "Image already exists, using it for cache"
          fi
          echo ${{ secrets.QT_EMAIL }} >> /tmp/qt_email && \
          echo ${{ secrets.QT_PASSWORD }} >> /tmp/qt_password && \
          docker build . \
            --file docker/${{ matrix.config.artifact }}.dockerfile \
            --tag ${{ steps.meta.outputs.tags }} \
            --build-arg ANDROID_SDK_VERSION=${{ env.ANDROID_SDK_VERSION }} \
            --build-arg ANDROID_BUILD_TOOLS_VERSION=${{ env.ANDROID_BUILD_TOOLS_VERSION }} \
            --build-arg ANDROID_NDK_VERSION=${{ env.ANDROID_NDK_VERSION }} \
            --build-arg QT_STABLE_VERSION=${{ env.QT_STABLE_VERSION }} \
            --secret id=QT_EMAIL,src=/tmp/qt_email \
            --secret id=QT_PASSWORD,src=/tmp/qt_password
          docker push ${{ steps.meta.outputs.tags }}

  build:
    name: ${{ matrix.config.artifact }}
    runs-on: ${{ matrix.config.os }}
    needs: docker
    container:
      image: ${{ matrix.config.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
      volumes:
        - .:/workspace
    outputs:
        tag: ${{ steps.git.outputs.tag }}
    strategy:
      fail-fast: true
      matrix:
        config:
        - {
            name: "Android arm64-v8",
            artifact: "android-arm64-v8",
            architecture: "arm64-v8a",
            image: "ghcr.io/xenosb/qt5/android-arm64-v8:${{ github.ref_name }}",
            os: ubuntu-latest,
            cc: "gcc", cxx: "g++"
          }
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout Qt repository
      uses: actions/checkout@v4
      with:
        ref: ${{ env.QT_VERSION }}
        fetch-depth: 1
        repository: Qt/qt5
        token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
        submodules: recursive

    - name: Configure Qt
      run: |
        mkdir -p build
        cd build
        ../configure \
          -nomake examples \
          -nomake tests \
          -release \
          -qt-host-path /opt/Qt/${{ env.QT_STABLE_VERSION }}/gcc_64 \
          -android-ndk ${{ env.ANDROID_SDK_ROOT }}/ndk/${{ env.ANDROID_NDK_VERSION }} \
          -android-sdk ${{ env.ANDROID_SDK_ROOT }} \
          -android-abis ${{ matrix.config.architecture }}

    - name: Build Qt
      run: |
        cmake \
          -S . \
          -B build \
          -DCMAKE_C_COMPILER_FRONTEND_VARIANT=GNU \
          -DCMAKE_CXX_COMPILER_FRONTEND_VARIANT=GNU \
          -DQT_GENERATE_WRAPPER_SCRIPTS_FOR_ALL_HOSTS=ON
        ninja \
          -C build
